---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  type: LoadBalancer
  ports:
    # TODO: Make functional
    - name: http
      port: 80
      targetPort: http
  selector:
  # TODO: Make functional
    app: redmine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  selector:
    matchLabels:
    # TODO: Make functional
      app: redmine
  replicas: 2
  template:
    metadata:
      labels:
      # TODO: Make functional
        app: redmine
    spec:
      containers:
      - name: redmine
        image: docker.io/bitnami/redmine:4.0.0
        imagePullPolicy: "IfNotPresent"
        env:
        # TODO: Make functional
        - name: REDMINE_DB_MYSQL
          value: mysql
        - name: REDMINE_DB_PASSWORD
          value: "password"
        - name: REDMINE_USERNAME
          value: "user"
        - name: REDMINE_PASSWORD
          value: "password"
        - name: REDMINE_EMAIL
          value: "user@test.com"
        - name: REDMINE_LANG
          value: "en"
        ports:
        # TODO: Make functional
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1

