kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-data
  labels:
    app: mariadb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
