apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: bitnami/mysql
    env:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: MYSQL_REPLICATION_MODE
      valueFrom:
        configMapKeyRef:
          name: mysql
          key: replication-mode
    - name: MYSQL_REPLICATION_USER
      valueFrom:
        configMapKeyRef:
          name: mysql
          key: replication-user
