# MySQL Configuration
- hosts: aws_backend

  become: true
  vars_files:
    - ../../default.yml
  tasks:
    - name: Install MySQL
      apt:
        pkg:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: latest
        update_cache: yes
    # - name: update mysql root password for all root accounts from local servers
    #   mysql_user:
    #     login_user: root
    #     login_password: "{{ mysql_root_password_old }}"
    #     name: root
    #     host: "{{ item }}"
    #     password: "{{ mysql_root_password }}"
    #     priv: "*.*:ALL,GRANT"
    #   with_items:
    #   - $ansible_hostname
    #   - 127.0.0.1
    #   - ::1
    #   - localhost
    # - name: Set the root password  (It only works at the first time)
    #   mysql_user:
    #     name: root
    #     password: "{{ mysql_root_password }}"
    #     login_unix_socket: /var/run/mysqld/mysqld.sock
    #     state: present
    #   tags: [ mysql, mysql-root ]

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Remove old_mysql user accounts
      mysql_user:
        name: "{{ mysql_old_user }}"
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        host: "{{ item.ip }}"
      with_items: "{{ frontend_hosts }}"
      tags: [ mysql ]
